import {
  User,
  StudentProfile,
  IndustryProfile,
  AcademicianProfile,
  Posting,
  LearningProgram,
  AcademicOpportunity,
  KnowledgeBaseItem,
  Application
} from '../types';

// Pre-seeded Users
export const initialUsers: User[] = [
  {
    id: 'user-stu-1',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@student.edu',
    role: 'student',
    institutionOrCompany: 'Indian Institute of Technology, Madras',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'user-stu-2',
    name: 'Priya Sundaram',
    email: 'priya.sundaram@student.edu',
    role: 'student',
    institutionOrCompany: 'National Institute of Technology, Trichy',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-18T10:00:00Z',
  },
  {
    id: 'user-stu-3',
    name: 'Rohan Gupta',
    email: 'rohan.gupta@student.edu',
    role: 'student',
    institutionOrCompany: 'BITS Pilani',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-02-01T11:30:00Z',
  },
  {
    id: 'user-stu-4',
    name: 'Meera Nambiar',
    email: 'meera.nambiar@student.edu',
    role: 'student',
    institutionOrCompany: 'Vellore Institute of Technology',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-02-05T09:15:00Z',
  },
  {
    id: 'user-stu-5',
    name: 'Devendra Joshi',
    email: 'devendra.joshi@student.edu',
    role: 'student',
    institutionOrCompany: 'Delhi Technological University',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-02-10T14:20:00Z',
  },
  // Industry Users
  {
    id: 'user-ind-1',
    name: 'Google Cloud Innovations',
    email: 'campus-relations@google.com',
    role: 'industry',
    institutionOrCompany: 'Google Cloud India',
    avatarUrl: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'user-ind-2',
    name: 'Siemens Industrial AI',
    email: 'careers@siemens-ai.de',
    role: 'industry',
    institutionOrCompany: 'Siemens Technology',
    avatarUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-12T11:00:00Z',
  },
  {
    id: 'user-ind-3',
    name: 'Tata Consultancy AI Labs',
    email: 'research-interns@tcs.com',
    role: 'industry',
    institutionOrCompany: 'Tata Consultancy Services',
    avatarUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-14T15:00:00Z',
  },
  {
    id: 'user-ind-4',
    name: 'Microsoft Ventures & Research',
    email: 'university-outreach@microsoft.com',
    role: 'industry',
    institutionOrCompany: 'Microsoft',
    avatarUrl: 'https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'user-ind-5',
    name: 'Infosys Center of AI Excellence',
    email: 'connect@infosys-ai.com',
    role: 'industry',
    institutionOrCompany: 'Infosys Labs',
    avatarUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-22T13:45:00Z',
  },
  // Academician Users
  {
    id: 'user-acad-1',
    name: 'Dr. Ramesh Kumar',
    email: 'ramesh.cs@iitm.ac.in',
    role: 'academician',
    institutionOrCompany: 'IIT Madras',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-05T09:00:00Z',
  },
  {
    id: 'user-acad-2',
    name: 'Dr. Shalini Verma',
    email: 'shalini.ai@nitt.edu',
    role: 'academician',
    institutionOrCompany: 'NIT Trichy',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-08T14:30:00Z',
  },
  {
    id: 'user-acad-3',
    name: 'Prof. Ananya Roy',
    email: 'ananya.roy@bits-pilani.ac.in',
    role: 'academician',
    institutionOrCompany: 'BITS Pilani',
    avatarUrl: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-11T12:00:00Z',
  },
  {
    id: 'user-acad-4',
    name: 'Dr. Vikram Mehta',
    email: 'vikram.mehta@dtu.ac.in',
    role: 'academician',
    institutionOrCompany: 'Delhi Technological University',
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-16T16:20:00Z',
  },
  {
    id: 'user-acad-5',
    name: 'Dr. Preeti Iyer',
    email: 'preeti.iyer@vit.ac.in',
    role: 'academician',
    institutionOrCompany: 'VIT Vellore',
    avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-19T10:10:00Z',
  },
  // Admin User
  {
    id: 'user-admin-1',
    name: 'National Admin — SkillBridge',
    email: 'admin@skillbridge.gov.in',
    role: 'admin',
    institutionOrCompany: 'Ministry of Education & NASSCOM FutureSkills',
    avatarUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-01T00:00:00Z',
  },
];

// Student Profiles
export const initialStudentProfiles: StudentProfile[] = [
  {
    userId: 'user-stu-1',
    fullName: 'Aarav Sharma',
    email: 'aarav.sharma@student.edu',
    branch: 'Computer Science & Engineering',
    year: '3rd Year',
    institution: 'IIT Madras',
    bio: 'Passionate full-stack developer and machine learning enthusiast. Looking for high-impact summer internships in generative AI, scalable cloud backend, and distributed systems.',
    gpa: '9.2 / 10',
    linkedinUrl: 'https://linkedin.com/in/aarav-sharma-demo',
    githubUrl: 'https://github.com/aaravsharma-dev',
    resumeUrl: 'https://skillbridge.edu/resumes/aarav_sharma_2026.pdf',
    targetRoles: ['Full-Stack AI Engineer', 'Cloud Backend Engineer', 'Machine Learning Intern'],
    skills: [
      { skillName: 'Python', proficiencyScore: 92, category: 'Programming', verified: true },
      { skillName: 'React & TypeScript', proficiencyScore: 88, category: 'Programming', verified: true },
      { skillName: 'Cloud & Kubernetes (GCP/AWS)', proficiencyScore: 72, category: 'Cloud & DevOps', verified: true },
      { skillName: 'Machine Learning (PyTorch/Scikit)', proficiencyScore: 85, category: 'AI & ML', verified: true },
      { skillName: 'SQL & Database Architecture', proficiencyScore: 80, category: 'Programming', verified: false },
      { skillName: 'System Design & Distributed Systems', proficiencyScore: 68, category: 'Core Engineering', verified: false },
      { skillName: 'Technical Communication', proficiencyScore: 85, category: 'Soft Skills', verified: true },
    ],
    portfolioProjects: [
      {
        id: 'proj-1',
        title: 'EduRAG: Institutional Knowledge Synthesis',
        description: 'Architected a multi-tenant RAG chatbot for universities using vector indexing over lecture PDFs, FastAPI backend, and Claude Sonnet integration.',
        technologies: ['Python', 'FastAPI', 'React', 'Firestore Vector Search', 'Anthropic API'],
        githubUrl: 'https://github.com/aaravsharma-dev/edurag',
        liveUrl: 'https://edurag-preview.web.app',
        verifiedBy: 'IIT Madras Innovation Cell',
      },
      {
        id: 'proj-2',
        title: 'Distributed Task Orchestrator in Go',
        description: 'Built a lightweight Raft-consensus job worker pool processing 10,000+ async events per second with automatic leader re-election.',
        technologies: ['Golang', 'Docker', 'Redis', 'gRPC'],
        githubUrl: 'https://github.com/aaravsharma-dev/dist-orch',
      },
    ],
    certifications: [
      {
        id: 'cert-1',
        title: 'Google Cloud Professional Cloud Architect',
        issuer: 'Google Cloud',
        issueDate: 'Jan 2026',
        credentialUrl: 'https://cloud.google.com/verify/GCP-849204',
        skillsVerified: ['Cloud & Kubernetes (GCP/AWS)', 'System Design'],
      },
      {
        id: 'cert-2',
        title: 'Deep Learning Specialization',
        issuer: 'DeepLearning.AI / Coursera',
        issueDate: 'Nov 2025',
        skillsVerified: ['Machine Learning (PyTorch/Scikit)', 'Python'],
      },
    ],
  },
  {
    userId: 'user-stu-2',
    fullName: 'Priya Sundaram',
    email: 'priya.sundaram@student.edu',
    branch: 'Data Science & Artificial Intelligence',
    year: '4th Year',
    institution: 'NIT Trichy',
    bio: 'Data Scientist specializing in Natural Language Processing and Predictive Analytics. Experienced in building production ML pipelines and automated data pipelines.',
    gpa: '9.4 / 10',
    linkedinUrl: 'https://linkedin.com/in/priya-sundaram',
    githubUrl: 'https://github.com/priyasundaram-ds',
    targetRoles: ['Data Scientist', 'NLP Engineer', 'Applied AI Researcher'],
    skills: [
      { skillName: 'Python', proficiencyScore: 95, category: 'Programming', verified: true },
      { skillName: 'Machine Learning (PyTorch/Scikit)', proficiencyScore: 92, category: 'AI & ML', verified: true },
      { skillName: 'SQL & Database Architecture', proficiencyScore: 90, category: 'Programming', verified: true },
      { skillName: 'Cloud & Kubernetes (GCP/AWS)', proficiencyScore: 65, category: 'Cloud & DevOps', verified: false },
      { skillName: 'Data Visualization (Recharts/Tableau)', proficiencyScore: 88, category: 'Design & UX', verified: true },
      { skillName: 'Critical Problem Solving', proficiencyScore: 92, category: 'Soft Skills', verified: true },
    ],
    portfolioProjects: [
      {
        id: 'proj-3',
        title: 'Clinical Named Entity Recognition Suite',
        description: 'Fine-tuned BioBERT transformer models on biomedical papers for automatic drug interaction extraction with 94.2% F1-score.',
        technologies: ['PyTorch', 'HuggingFace', 'FastAPI', 'Docker'],
        githubUrl: 'https://github.com/priyasundaram-ds/clinical-ner',
      }
    ],
    certifications: [
      {
        id: 'cert-3',
        title: 'NVIDIA Certified Associate: Generative AI & LLMs',
        issuer: 'NVIDIA Deep Learning Institute',
        issueDate: 'Dec 2025',
        skillsVerified: ['Machine Learning (PyTorch/Scikit)', 'Python'],
      }
    ],
  },
];

// Industry Profiles
export const initialIndustryProfiles: IndustryProfile[] = [
  {
    userId: 'user-ind-1',
    companyName: 'Google Cloud Innovations',
    industryType: 'Cloud & Enterprise AI',
    website: 'https://cloud.google.com',
    location: 'Bengaluru & Hyderabad, India',
    logoUrl: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=100&auto=format&fit=crop&q=80',
    description: 'Empowering organizations worldwide with cutting-edge cloud infrastructure, Vertex AI, and enterprise generative AI solutions.',
    verified: true,
    contactEmail: 'campus-relations@google.com',
  },
  {
    userId: 'user-ind-2',
    companyName: 'Siemens Industrial AI',
    industryType: 'Industrial IoT & Automation',
    website: 'https://siemens.com',
    location: 'Bengaluru, India / Munich, Germany',
    logoUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=100&auto=format&fit=crop&q=80',
    description: 'Transforming factories and smart infrastructure with real-time sensor analytics, digital twins, and industrial robotics.',
    verified: true,
    contactEmail: 'careers@siemens-ai.de',
  },
  {
    userId: 'user-ind-3',
    companyName: 'Tata Consultancy AI Labs',
    industryType: 'IT Services & Digital Transformation',
    website: 'https://tcs.com',
    location: 'Mumbai, Pune, Chennai, India',
    logoUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=100&auto=format&fit=crop&q=80',
    description: 'Pioneering enterprise AI workflows, automated DevOps, and academic research collaborations across India.',
    verified: true,
    contactEmail: 'research-interns@tcs.com',
  },
  {
    userId: 'user-ind-4',
    companyName: 'Microsoft Ventures & Research',
    industryType: 'Software & Cloud Computing',
    website: 'https://microsoft.com',
    location: 'Hyderabad & Bengaluru, India',
    logoUrl: 'https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=100&auto=format&fit=crop&q=80',
    description: 'Advancing research in large language models, Azure quantum systems, and developer tooling ecosystems.',
    verified: true,
    contactEmail: 'university-outreach@microsoft.com',
  },
  {
    userId: 'user-ind-5',
    companyName: 'Infosys Center of AI Excellence',
    industryType: 'Information Technology & Consulting',
    website: 'https://infosys.com',
    location: 'Bengaluru & Mysore, India',
    logoUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=100&auto=format&fit=crop&q=80',
    description: 'Building next-generation generative AI solutions for banking, retail, and manufacturing sectors.',
    verified: true,
    contactEmail: 'connect@infosys-ai.com',
  },
];

// Academician Profiles
export const initialAcademicianProfiles: AcademicianProfile[] = [
  {
    userId: 'user-acad-1',
    fullName: 'Dr. Ramesh Kumar',
    department: 'Computer Science & Engineering',
    designation: 'HOD & Professor',
    institution: 'IIT Madras',
    researchAreas: ['Distributed Systems', 'Cloud Computing', 'Computer Networks'],
    experienceYears: 18,
    bio: 'Lead researcher in high-throughput cloud networks. Passionate about bridging industry cloud requirements with university curriculum.',
    publicationsCount: 42,
  },
  {
    userId: 'user-acad-2',
    fullName: 'Dr. Shalini Verma',
    department: 'Data Science & AI',
    designation: 'Associate Professor',
    institution: 'NIT Trichy',
    researchAreas: ['Natural Language Processing', 'Generative AI', 'Computer Vision'],
    experienceYears: 12,
    bio: 'Chairing the AI Research Lab at NIT Trichy with focus on multimodal transformer architectures and responsible AI.',
    publicationsCount: 28,
  },
  {
    userId: 'user-acad-3',
    fullName: 'Prof. Ananya Roy',
    department: 'Information Systems',
    designation: 'Assistant Professor',
    institution: 'BITS Pilani',
    researchAreas: ['Cybersecurity', 'Blockchain', 'Privacy-Preserving Computation'],
    experienceYears: 8,
    bio: 'Dedicated educator specializing in applied cryptography and collaborative industry security audits.',
    publicationsCount: 16,
  },
];

// 20 Job & Internship Postings
export const initialPostings: Posting[] = [
  {
    id: 'post-1',
    industryId: 'user-ind-1',
    companyName: 'Google Cloud Innovations',
    type: 'Internship',
    title: 'Generative AI & Cloud Architecture Summer Intern',
    description: 'Join the Google Cloud engineering group to build enterprise RAG pipelines, deploy Vertex AI search models, and design fault-tolerant microservices on Kubernetes.',
    requiredSkills: [
      { skillName: 'Python', minScore: 80 },
      { skillName: 'Cloud & Kubernetes (GCP/AWS)', minScore: 75 },
      { skillName: 'Machine Learning (PyTorch/Scikit)', minScore: 70 },
      { skillName: 'SQL & Database Architecture', minScore: 70 },
    ],
    location: 'Bengaluru, India',
    isRemote: false,
    stipendOrSalary: '₹95,000 / month',
    duration: '3 Months (May – July 2026)',
    deadline: '2026-04-15',
    createdAt: '2026-02-15T10:00:00Z',
    applicantCount: 24,
    status: 'active',
  },
  {
    id: 'post-2',
    industryId: 'user-ind-1',
    companyName: 'Google Cloud Innovations',
    type: 'Job',
    title: 'Associate Cloud Solutions Architect (Freshers)',
    description: 'Partner with enterprise clients to architect modern cloud migrations, serverless workflows, and data pipelines on Google Cloud Platform.',
    requiredSkills: [
      { skillName: 'Cloud & Kubernetes (GCP/AWS)', minScore: 80 },
      { skillName: 'Python', minScore: 75 },
      { skillName: 'System Design & Distributed Systems', minScore: 75 },
      { skillName: 'Technical Communication', minScore: 80 },
    ],
    location: 'Hyderabad, India',
    isRemote: false,
    stipendOrSalary: '₹22,00,000 / year CTC',
    duration: 'Full-Time',
    deadline: '2026-04-30',
    createdAt: '2026-02-18T14:30:00Z',
    applicantCount: 42,
    status: 'active',
  },
  {
    id: 'post-3',
    industryId: 'user-ind-2',
    companyName: 'Siemens Industrial AI',
    type: 'Internship',
    title: 'Industrial Computer Vision & Robotics Intern',
    description: 'Develop edge AI models for real-time defect detection on manufacturing assembly lines using OpenCV, TensorRT, and C++/Python.',
    requiredSkills: [
      { skillName: 'Python', minScore: 85 },
      { skillName: 'Machine Learning (PyTorch/Scikit)', minScore: 80 },
      { skillName: 'Core Engineering', minScore: 70 },
    ],
    location: 'Bengaluru, India (Hybrid)',
    isRemote: false,
    stipendOrSalary: '₹65,000 / month',
    duration: '6 Months',
    deadline: '2026-04-20',
    createdAt: '2026-02-20T09:00:00Z',
    applicantCount: 18,
    status: 'active',
  },
  {
    id: 'post-4',
    industryId: 'user-ind-3',
    companyName: 'Tata Consultancy AI Labs',
    type: 'Internship',
    title: 'NLP & Foundation Models Research Intern',
    description: 'Work alongside lead scientists fine-tuning Indic language LLMs, building domain-specific embeddings, and benchmark evaluations.',
    requiredSkills: [
      { skillName: 'Python', minScore: 85 },
      { skillName: 'Machine Learning (PyTorch/Scikit)', minScore: 85 },
      { skillName: 'SQL & Database Architecture', minScore: 65 },
    ],
    location: 'Pune / Mumbai, India',
    isRemote: true,
    stipendOrSalary: '₹55,000 / month',
    duration: '4 Months',
    deadline: '2026-04-25',
    createdAt: '2026-02-22T11:20:00Z',
    applicantCount: 31,
    status: 'active',
  },
  {
    id: 'post-5',
    industryId: 'user-ind-4',
    companyName: 'Microsoft Ventures & Research',
    type: 'Internship',
    title: 'Modern Frontend & Developer Tools Intern (React/TS)',
    description: 'Craft high-performance web interfaces and developer SDKs with React, TypeScript, Tailwind, and WebAssembly.',
    requiredSkills: [
      { skillName: 'React & TypeScript', minScore: 85 },
      { skillName: 'Technical Communication', minScore: 75 },
      { skillName: 'SQL & Database Architecture', minScore: 60 },
    ],
    location: 'Hyderabad, India',
    isRemote: true,
    stipendOrSalary: '₹85,000 / month',
    duration: '3 Months',
    deadline: '2026-04-10',
    createdAt: '2026-02-25T15:00:00Z',
    applicantCount: 39,
    status: 'active',
  },
  {
    id: 'post-6',
    industryId: 'user-ind-5',
    companyName: 'Infosys Center of AI Excellence',
    type: 'Job',
    title: 'Full Stack AI Engineer (Graduate Program 2026)',
    description: 'Build enterprise web platforms integrated with LLM agents, vector databases, and responsive modern dashboards.',
    requiredSkills: [
      { skillName: 'Python', minScore: 75 },
      { skillName: 'React & TypeScript', minScore: 75 },
      { skillName: 'SQL & Database Architecture', minScore: 70 },
      { skillName: 'Cloud & Kubernetes (GCP/AWS)', minScore: 65 },
    ],
    location: 'Mysore / Bengaluru, India',
    isRemote: false,
    stipendOrSalary: '₹14,50,000 / year CTC',
    duration: 'Full-Time',
    deadline: '2026-05-01',
    createdAt: '2026-02-26T08:00:00Z',
    applicantCount: 56,
    status: 'active',
  },
  {
    id: 'post-7',
    industryId: 'user-ind-2',
    companyName: 'Siemens Industrial AI',
    type: 'Job',
    title: 'Industrial IoT & Edge Systems Developer',
    description: 'Develop low-latency firmware and edge compute drivers for industrial IoT gateways communicating over MQTT, OPC-UA, and Modbus.',
    requiredSkills: [
      { skillName: 'Core Engineering', minScore: 80 },
      { skillName: 'Python', minScore: 75 },
      { skillName: 'System Design & Distributed Systems', minScore: 70 },
    ],
    location: 'Bengaluru, India',
    isRemote: false,
    stipendOrSalary: '₹16,00,000 / year CTC',
    duration: 'Full-Time',
    deadline: '2026-05-15',
    createdAt: '2026-03-01T12:00:00Z',
    applicantCount: 15,
    status: 'active',
  },
  {
    id: 'post-8',
    industryId: 'user-ind-4',
    companyName: 'Microsoft Ventures & Research',
    type: 'Job',
    title: 'Security & Cloud Compliance Engineer',
    description: 'Implement zero-trust architectures, automated compliance scanning, and vulnerability triage across multi-region Azure environments.',
    requiredSkills: [
      { skillName: 'Cloud & Kubernetes (GCP/AWS)', minScore: 85 },
      { skillName: 'Python', minScore: 75 },
      { skillName: 'System Design & Distributed Systems', minScore: 80 },
    ],
    location: 'Hyderabad, India',
    isRemote: false,
    stipendOrSalary: '₹24,00,000 / year CTC',
    duration: 'Full-Time',
    deadline: '2026-05-10',
    createdAt: '2026-03-02T16:00:00Z',
    applicantCount: 20,
    status: 'active',
  },
  {
    id: 'post-9',
    industryId: 'user-ind-1',
    companyName: 'Google Cloud Innovations',
    type: 'Internship',
    title: 'Data Platform & Distributed Storage Intern',
    description: 'Optimize BigQuery connectors, Parquet compression pipelines, and streaming ingestion using Apache Beam.',
    requiredSkills: [
      { skillName: 'Python', minScore: 80 },
      { skillName: 'SQL & Database Architecture', minScore: 85 },
      { skillName: 'Cloud & Kubernetes (GCP/AWS)', minScore: 70 },
    ],
    location: 'Bengaluru, India',
    isRemote: true,
    stipendOrSalary: '₹90,000 / month',
    duration: '3 Months',
    deadline: '2026-04-18',
    createdAt: '2026-03-03T10:00:00Z',
    applicantCount: 28,
    status: 'active',
  },
  {
    id: 'post-10',
    industryId: 'user-ind-3',
    companyName: 'Tata Consultancy AI Labs',
    type: 'Apprenticeship',
    title: 'Enterprise AI Apprentice — NextGen Engineers',
    description: 'One-year immersive program with dedicated mentorship in deep learning model serving, prompt engineering, and synthetic data generation.',
    requiredSkills: [
      { skillName: 'Python', minScore: 70 },
      { skillName: 'Machine Learning (PyTorch/Scikit)', minScore: 65 },
      { skillName: 'Technical Communication', minScore: 70 },
    ],
    location: 'Chennai, India',
    isRemote: false,
    stipendOrSalary: '₹40,000 / month',
    duration: '12 Months',
    deadline: '2026-05-20',
    createdAt: '2026-03-04T09:00:00Z',
    applicantCount: 65,
    status: 'active',
  },
  {
    id: 'post-11',
    industryId: 'user-ind-5',
    companyName: 'Infosys Center of AI Excellence',
    type: 'Internship',
    title: 'UI/UX Design & Front-End Innovation Intern',
    description: 'Design intuitive workflows for AI agent configuration, data visualization dashboards, and modern component systems in Figma & React.',
    requiredSkills: [
      { skillName: 'React & TypeScript', minScore: 80 },
      { skillName: 'Data Visualization (Recharts/Tableau)', minScore: 80 },
      { skillName: 'Technical Communication', minScore: 75 },
    ],
    location: 'Bengaluru, India (Hybrid)',
    isRemote: false,
    stipendOrSalary: '₹50,000 / month',
    duration: '3 Months',
    deadline: '2026-04-28',
    createdAt: '2026-03-05T14:00:00Z',
    applicantCount: 22,
    status: 'active',
  },
  {
    id: 'post-12',
    industryId: 'user-ind-4',
    companyName: 'Microsoft Ventures & Research',
    type: 'Internship',
    title: 'Reinforcement Learning for Autonomous Agents Intern',
    description: 'Research state-of-the-art policy optimization algorithms for web-browsing agentic systems and multi-step reasoning.',
    requiredSkills: [
      { skillName: 'Python', minScore: 90 },
      { skillName: 'Machine Learning (PyTorch/Scikit)', minScore: 88 },
      { skillName: 'System Design & Distributed Systems', minScore: 70 },
    ],
    location: 'Bengaluru, India',
    isRemote: true,
    stipendOrSalary: '₹95,000 / month',
    duration: '6 Months',
    deadline: '2026-04-30',
    createdAt: '2026-03-06T11:00:00Z',
    applicantCount: 19,
    status: 'active',
  },
];

// 10 Industry Learning Programs
export const initialLearningPrograms: LearningProgram[] = [
  {
    id: 'prog-1',
    industryId: 'user-ind-1',
    companyName: 'Google Cloud Innovations',
    title: 'Google Cloud Certified Associate Cloud Engineer Masterclass',
    description: 'Comprehensive industry course covering VPC networks, Kubernetes clusters (GKE), IAM governance, and BigQuery analytics.',
    skillsCovered: ['Cloud & Kubernetes (GCP/AWS)', 'System Design & Distributed Systems', 'DevOps'],
    targetSkill: 'Cloud & Kubernetes (GCP/AWS)',
    skillBoostScore: 15,
    duration: '4 Weeks (20 Hours)',
    mode: 'Self-Paced',
    level: 'Intermediate',
    enrolledCount: 340,
    instructor: 'Satish Rao, Lead Cloud Architect @ Google',
    link: 'https://cloud.google.com/training/ace-masterclass',
    syllabus: [
      'Setting up Cloud Solution Environments',
      'Configuring and Deploying Compute Engine & Kubernetes Engine',
      'Storage Solutions: Cloud Storage, Firestore & Cloud SQL',
      'Security, Monitoring & Observability with Cloud Logging',
    ],
  },
  {
    id: 'prog-2',
    industryId: 'user-ind-3',
    companyName: 'Tata Consultancy AI Labs',
    title: 'Production LLMs & Enterprise RAG Engineering',
    description: 'Learn how to build, evaluate, and scale retrieval-augmented generation chatbots using vector databases, semantic search, and Anthropic Claude.',
    skillsCovered: ['Machine Learning (PyTorch/Scikit)', 'Python', 'Vector Search'],
    targetSkill: 'Machine Learning (PyTorch/Scikit)',
    skillBoostScore: 18,
    duration: '3 Weeks (15 Hours)',
    mode: 'Hybrid',
    level: 'Advanced',
    enrolledCount: 480,
    instructor: 'Dr. Meenakshi S., Principal AI Researcher @ TCS',
    link: 'https://tcs.com/learning/rag-mastery',
    syllabus: [
      'Embeddings & Vector Store Architecture (Firestore Vector Search / Chroma)',
      'Chunking Strategies and Semantic Filtering',
      'Prompt Optimization & Grounded Citations',
      'Guardrails, Latency Optimization & LLM Evals',
    ],
  },
  {
    id: 'prog-3',
    industryId: 'user-ind-4',
    companyName: 'Microsoft Ventures & Research',
    title: 'Full-Stack Modern React & TypeScript Architecture',
    description: 'Master professional React 19 patterns, state management, server components, Tailwind design systems, and automated testing.',
    skillsCovered: ['React & TypeScript', 'Design & UX', 'Modern Web Standards'],
    targetSkill: 'React & TypeScript',
    skillBoostScore: 16,
    duration: '5 Weeks (25 Hours)',
    mode: 'Self-Paced',
    level: 'Intermediate',
    enrolledCount: 620,
    instructor: 'Kunal Singhal, Staff Engineer @ Microsoft',
    link: 'https://microsoft.com/learn/fullstack-react-ts',
    syllabus: [
      'Advanced TypeScript Generics & Type Guards',
      'Performant State Management & Hooks Architecture',
      'Building Accessible Design Systems with Tailwind CSS',
      'End-to-End Type Safety & API Integration',
    ],
  },
  {
    id: 'prog-4',
    industryId: 'user-ind-2',
    companyName: 'Siemens Industrial AI',
    title: 'Industrial IoT & Edge Computer Vision Bootcamp',
    description: 'Hands-on edge AI model deployment on Raspberry Pi / NVIDIA Jetson devices with real-time video stream processing.',
    skillsCovered: ['Core Engineering', 'Python', 'Computer Vision'],
    targetSkill: 'Core Engineering',
    skillBoostScore: 14,
    duration: '4 Weeks (18 Hours)',
    mode: 'Live Cohort',
    level: 'Intermediate',
    enrolledCount: 210,
    instructor: 'Florian Wagner, Lead IoT Scientist @ Siemens',
    link: 'https://siemens.com/training/iiot-bootcamp',
    syllabus: [
      'Sensors, Industrial Protocols & MQTT Telemetry',
      'Edge Inference Optimization with TensorRT & ONNX',
      'Real-time Stream Pipeline with OpenCV & RTSP',
      'Cloud Synchronization & Digital Twin Modeling',
    ],
  },
  {
    id: 'prog-5',
    industryId: 'user-ind-5',
    companyName: 'Infosys Center of AI Excellence',
    title: 'High-Performance SQL & Database Optimization',
    description: 'Deep-dive into query execution plans, indexing strategies, partition sharding, and ACID transaction isolation levels.',
    skillsCovered: ['SQL & Database Architecture', 'System Design & Distributed Systems'],
    targetSkill: 'SQL & Database Architecture',
    skillBoostScore: 12,
    duration: '2 Weeks (10 Hours)',
    mode: 'Self-Paced',
    level: 'Beginner',
    enrolledCount: 510,
    instructor: 'Pooja Hegde, Chief Data Architect @ Infosys',
    link: 'https://infosys.com/springboard/sql-mastery',
    syllabus: [
      'Relational Schema Design & Normalization',
      'B-Tree and Hash Indexes Under the Hood',
      'Analyzing EXPLAIN Query Execution Plans',
      'NoSQL and Distributed Key-Value Store Architectures',
    ],
  },
  {
    id: 'prog-6',
    industryId: 'user-ind-1',
    companyName: 'Google Cloud Innovations',
    title: 'System Design for Distributed & Scalable Backends',
    description: 'Learn how to design scalable architectures handling 100M+ DAU, message brokers (Kafka/PubSub), caching strategies, and CAP theorem trade-offs.',
    skillsCovered: ['System Design & Distributed Systems', 'Cloud & Kubernetes (GCP/AWS)'],
    targetSkill: 'System Design & Distributed Systems',
    skillBoostScore: 15,
    duration: '4 Weeks (20 Hours)',
    mode: 'Self-Paced',
    level: 'Advanced',
    enrolledCount: 780,
    instructor: 'Arjun N., Senior Principal Engineer @ Google',
    link: 'https://cloud.google.com/learn/system-design',
    syllabus: [
      'Load Balancing & Consistent Hashing',
      'Distributed Caching & Cache Invalidation',
      'Event-Driven Architectures with Kafka',
      'Consensus Protocols (Paxos, Raft)',
    ],
  },
];

// 10 Academic Opportunities (FDPs, Consultancy, Joint Research)
export const initialAcademicOpportunities: AcademicOpportunity[] = [
  {
    id: 'acad-opp-1',
    postedById: 'user-ind-1',
    postedByName: 'Google Cloud Innovations',
    companyOrOrg: 'Google Cloud India',
    type: 'FDP',
    title: 'National Faculty Development Program on Generative AI & Cloud Curriculum',
    description: 'A 5-day immersive faculty enablement program for Computer Science & IT professors to integrate Google Cloud Vertex AI, LLM prompting, and modern RAG architectures into undergraduate curricula.',
    domain: 'Cloud Computing & Generative AI',
    duration: '5 Days (Virtual & Interactive Labs)',
    location: 'Virtual / Online',
    isVirtual: true,
    honorariumOrGrant: 'Sponsored Training + 500 Google Cloud Lab Credits / Faculty',
    eligibility: 'Faculty teaching CSE, IT, AI&DS, or ECE in recognized engineering colleges.',
    deadline: '2026-04-10',
    createdAt: '2026-02-15T09:00:00Z',
    status: 'open',
  },
  {
    id: 'acad-opp-2',
    postedById: 'user-ind-2',
    postedByName: 'Siemens Industrial AI',
    companyOrOrg: 'Siemens Technology India',
    type: 'Industrial Training',
    title: 'Industrial Fellowship on Cyber-Physical Systems & Smart Manufacturing',
    description: 'Faculty immersion program at Siemens Bangalore R&D center to gain first-hand industrial automation experience, hardware-in-the-loop simulation, and real-world industrial IoT workflows.',
    domain: 'Industrial Automation & IoT',
    duration: '3 Weeks (On-site Summer 2026)',
    location: 'Bengaluru, India',
    isVirtual: false,
    honorariumOrGrant: '₹75,000 Travel & Accommodation Grant',
    eligibility: 'Assistant & Associate Professors in Mechanical, Mechatronics, EEE, ECE.',
    deadline: '2026-04-25',
    createdAt: '2026-02-20T11:00:00Z',
    status: 'open',
  },
  {
    id: 'acad-opp-3',
    postedById: 'user-ind-3',
    postedByName: 'Tata Consultancy AI Labs',
    companyOrOrg: 'TCS Research & Innovation',
    type: 'Consultancy',
    title: 'Industry Consultancy: Indian Multilingual NLP Benchmark Evaluation',
    description: 'Seeking faculty domain experts to consult on linguistic validation, bias evaluation, and syntax parsing for vernacular speech and text foundation models across 12 Indian languages.',
    domain: 'Computational Linguistics & NLP',
    duration: '6 Months Project (Part-Time)',
    location: 'Hybrid / Flexible',
    isVirtual: true,
    honorariumOrGrant: '₹4,50,000 Institutional Consultancy Retainer',
    eligibility: 'Ph.D. holders in NLP, Linguistics, or Artificial Intelligence.',
    deadline: '2026-04-30',
    createdAt: '2026-02-25T14:30:00Z',
    status: 'open',
  },
  {
    id: 'acad-opp-4',
    postedById: 'user-ind-4',
    postedByName: 'Microsoft Ventures & Research',
    companyOrOrg: 'Microsoft Academic Outreach',
    type: 'Joint Research',
    title: 'Joint Research Grant: Privacy-Preserving Federated Learning for Healthcare',
    description: 'Call for collaborative research proposals with Indian universities to co-develop differential privacy algorithms for distributed medical imaging datasets.',
    domain: 'Privacy-Preserving AI & Healthcare',
    duration: '12 Months Collaborative Grant',
    location: 'Virtual / Campus Collaboration',
    isVirtual: true,
    honorariumOrGrant: '₹12,00,000 Research Grant + Azure Compute Cloud Credits',
    eligibility: 'University Departments with active postgraduate research labs.',
    deadline: '2026-05-15',
    createdAt: '2026-03-01T10:00:00Z',
    status: 'open',
  },
];

// Initial Applications
export const initialApplications: Application[] = [
  {
    id: 'app-1',
    studentId: 'user-stu-1',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@student.edu',
    studentBranch: 'Computer Science',
    studentYear: '3rd Year',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    postingId: 'post-1',
    postingTitle: 'Generative AI & Cloud Architecture Summer Intern',
    companyName: 'Google Cloud Innovations',
    status: 'Interview',
    matchScore: 92,
    appliedAt: '2026-02-20T11:00:00Z',
    coverNote: 'I have hands-on experience building RAG architectures and deploying containerized services on GCP. Excited to contribute to Google Cloud enterprise AI tools!',
  },
  {
    id: 'app-2',
    studentId: 'user-stu-1',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@student.edu',
    studentBranch: 'Computer Science',
    studentYear: '3rd Year',
    postingId: 'post-5',
    postingTitle: 'Modern Frontend & Developer Tools Intern (React/TS)',
    companyName: 'Microsoft Ventures & Research',
    status: 'Shortlisted',
    matchScore: 89,
    appliedAt: '2026-02-28T14:15:00Z',
  },
  {
    id: 'app-3',
    studentId: 'user-stu-2',
    studentName: 'Priya Sundaram',
    studentEmail: 'priya.sundaram@student.edu',
    studentBranch: 'Data Science & AI',
    studentYear: '4th Year',
    postingId: 'post-4',
    postingTitle: 'NLP & Foundation Models Research Intern',
    companyName: 'Tata Consultancy AI Labs',
    status: 'Offer',
    matchScore: 96,
    appliedAt: '2026-02-24T09:30:00Z',
  },
];

// 15 Knowledge Base Entries for RAG with Pre-generated Semantic Embeddings
export const initialKnowledgeBase: KnowledgeBaseItem[] = [
  {
    id: 'kb-1',
    title: 'Cloud & Kubernetes Industry Benchmark Requirements',
    category: 'Industry Benchmark',
    sourceType: 'skill',
    content: 'Leading enterprise cloud companies require students to have hands-on experience with containerization (Docker), cluster orchestration (Kubernetes / GKE / EKS), Infrastructure as Code (Terraform), and CI/CD pipelines. A minimum proficiency score of 75% in Cloud & Kubernetes is recommended for cloud engineering internships at Google Cloud, Microsoft Azure, and Amazon Web Services.',
    tags: ['cloud', 'kubernetes', 'docker', 'gcp', 'aws', 'devops', 'internships'],
    updatedAt: '2026-03-01T00:00:00Z',
    embedding: [0.12, 0.85, 0.44, 0.91, 0.33, 0.65, 0.78, 0.22, 0.54, 0.89, 0.15, 0.42, 0.77, 0.63, 0.29, 0.94],
  },
  {
    id: 'kb-2',
    title: 'Bridging the Machine Learning to Production (MLOps) Skill Gap',
    category: 'Skill Guidance',
    sourceType: 'skill',
    content: 'While 85% of computer science students study theoretical machine learning algorithms (linear regression, SVMs, CNNs), industry hiring managers report that only 18% of candidates know how to package models into REST APIs, optimize inference latency with ONNX or TensorRT, and implement vector databases for Retrieval-Augmented Generation (RAG). Students can bridge this gap by taking hands-on industry masterclasses like the TCS Production LLMs Masterclass.',
    tags: ['ml', 'machine learning', 'mlops', 'rag', 'vector database', 'gap report', 'courses'],
    updatedAt: '2026-03-01T00:00:00Z',
    embedding: [0.88, 0.32, 0.79, 0.45, 0.92, 0.81, 0.35, 0.67, 0.84, 0.29, 0.75, 0.88, 0.43, 0.51, 0.90, 0.38],
  },
  {
    id: 'kb-3',
    title: 'Google Cloud Innovations — Summer Internship Eligibility & Selection',
    category: 'Opportunity',
    sourceType: 'posting',
    sourceRefId: 'post-1',
    content: 'The Google Cloud Summer Internship 2026 offers ₹95,000/month stipend for 3rd and 4th year undergraduate and postgraduate students. Key evaluation criteria include proficiency in Python (80%+), Cloud & Kubernetes (75%+), and Database Architecture (70%+). Applicants who have completed certified projects with live URLs or public GitHub repositories receive priority ranking in the SkillBridge candidate matching algorithm.',
    tags: ['google cloud', 'internship', 'python', 'stipend', 'summer 2026', 'hiring'],
    updatedAt: '2026-03-01T00:00:00Z',
    embedding: [0.25, 0.92, 0.55, 0.88, 0.41, 0.71, 0.82, 0.19, 0.62, 0.93, 0.28, 0.50, 0.81, 0.70, 0.35, 0.91],
  },
  {
    id: 'kb-4',
    title: 'Faculty Development Programs (FDP) Roadmap for Engineering Institutions',
    category: 'Curriculum Sync',
    sourceType: 'opportunity',
    sourceRefId: 'acad-opp-1',
    content: 'National FDP on Generative AI & Cloud Curriculum sponsored by Google Cloud India empowers faculty members to modernize laboratory assignments. Participating academicians receive 500 Google Cloud compute credits and access to standardized syllabi for teaching transformer architectures, vector embeddings, and serverless application hosting.',
    tags: ['faculty', 'academician', 'fdp', 'google cloud', 'curriculum', 'credits'],
    updatedAt: '2026-03-01T00:00:00Z',
    embedding: [0.42, 0.76, 0.38, 0.65, 0.59, 0.49, 0.83, 0.71, 0.39, 0.62, 0.84, 0.55, 0.68, 0.90, 0.47, 0.61],
  },
  {
    id: 'kb-5',
    title: 'Full-Stack Developer Career Pathway & In-Demand Tech Stack',
    category: 'Career Pathway',
    sourceType: 'skill',
    content: 'The 2026 modern full-stack developer profile is defined by type-safe architecture using React 19, TypeScript, Tailwind CSS on the frontend, combined with Node.js/Python microservices, GraphQL or RESTful endpoints, and NoSQL databases like Firestore or MongoDB. High proficiency in TypeScript and Component Design provides a 3.4x higher interview callback rate.',
    tags: ['react', 'typescript', 'frontend', 'fullstack', 'career', 'tailwind', 'javascript'],
    updatedAt: '2026-03-01T00:00:00Z',
    embedding: [0.72, 0.41, 0.88, 0.39, 0.64, 0.89, 0.31, 0.58, 0.77, 0.34, 0.68, 0.82, 0.49, 0.55, 0.86, 0.44],
  },
  {
    id: 'kb-6',
    title: 'TCS Production LLMs & RAG Course Details & Skill Boost',
    category: 'Skill Guidance',
    sourceType: 'program',
    sourceRefId: 'prog-2',
    content: 'The TCS Production LLMs & Enterprise RAG Engineering program is a 3-week advanced course led by Principal AI Scientists. Completing all module quizzes and capstone project awards a verified SkillBridge badge and provides a +18 point proficiency boost to the student Machine Learning skill score.',
    tags: ['tcs', 'rag', 'llm', 'learning program', 'skill boost', 'badge', 'free course'],
    updatedAt: '2026-03-01T00:00:00Z',
    embedding: [0.85, 0.38, 0.74, 0.52, 0.90, 0.78, 0.40, 0.63, 0.81, 0.35, 0.72, 0.85, 0.48, 0.57, 0.88, 0.42],
  },
  {
    id: 'kb-7',
    title: 'Siemens Industrial Fellowship for Engineering Faculty',
    category: 'Opportunity',
    sourceType: 'opportunity',
    sourceRefId: 'acad-opp-2',
    content: 'Siemens Technology offers a 3-week on-site summer fellowship in Bengaluru for Assistant & Associate Professors. Includes ₹75,000 accommodation grant, access to industrial robotics labs, digital twin testbeds, and direct co-supervision of student capstone projects.',
    tags: ['siemens', 'fellowship', 'academician', 'grant', 'robotics', 'iot'],
    updatedAt: '2026-03-01T00:00:00Z',
    embedding: [0.35, 0.68, 0.42, 0.73, 0.51, 0.55, 0.79, 0.65, 0.46, 0.69, 0.78, 0.61, 0.72, 0.85, 0.53, 0.67],
  },
  {
    id: 'kb-8',
    title: 'Skill Assessment & Radar Chart Proficiency Calculation',
    category: 'Skill Guidance',
    sourceType: 'skill',
    content: 'The SkillBridge diagnostic assessment evaluates students across 6 core competency domains on a 0-100 scale using Likert-scale self-evaluations, domain code challenges, and project verification. The Radar Chart visually contrasts individual candidate scores against target role benchmarks to pinpoint exact skill gaps.',
    tags: ['assessment', 'radar chart', 'skill score', 'gap analysis', 'evaluation'],
    updatedAt: '2026-03-01T00:00:00Z',
    embedding: [0.60, 0.55, 0.68, 0.59, 0.71, 0.64, 0.58, 0.52, 0.63, 0.57, 0.66, 0.61, 0.59, 0.65, 0.62, 0.58],
  },
  {
    id: 'kb-9',
    title: 'Digital Portfolio Verification and Shareable Link System',
    category: 'Career Pathway',
    sourceType: 'skill',
    content: 'Students can generate a tamper-proof digital portfolio featuring verified skills, project repositories, institution credentials, and industry course badges. The public portfolio URL format `/portfolio/:studentId` allows recruiters to inspect verified skill vectors directly without requiring traditional resumes.',
    tags: ['portfolio', 'pdf export', 'public link', 'verification', 'badges', 'resume'],
    updatedAt: '2026-03-01T00:00:00Z',
    embedding: [0.52, 0.62, 0.75, 0.48, 0.67, 0.73, 0.45, 0.59, 0.69, 0.48, 0.71, 0.70, 0.54, 0.61, 0.74, 0.50],
  },
  {
    id: 'kb-10',
    title: 'Microsoft Ventures NLP & RL Research Opportunities',
    category: 'Opportunity',
    sourceType: 'posting',
    sourceRefId: 'post-12',
    content: 'Microsoft Ventures & Research offers high-stipend (₹95,000/mo) 6-month internships in Reinforcement Learning for Autonomous Agents. Requires high competency in Python (90%+), PyTorch (88%+), and Distributed Systems fundamentals.',
    tags: ['microsoft', 'research', 'reinforcement learning', 'internship', 'stipend'],
    updatedAt: '2026-03-01T00:00:00Z',
    embedding: [0.82, 0.44, 0.81, 0.49, 0.94, 0.85, 0.38, 0.69, 0.86, 0.32, 0.78, 0.91, 0.46, 0.53, 0.92, 0.40],
  },
  {
    id: 'kb-11',
    title: 'Academician Consultancy Honorariums & Grant Compliance',
    category: 'Curriculum Sync',
    sourceType: 'opportunity',
    sourceRefId: 'acad-opp-3',
    content: 'Faculty consultancy projects hosted on SkillBridge comply with standard university revenue-sharing and UGC/AICTE intellectual property policies. Honorariums are processed transparently with automatic generation of institutional approval letters and deliverables tracking.',
    tags: ['consultancy', 'grant', 'honorarium', 'ugc', 'aicte', 'academician'],
    updatedAt: '2026-03-01T00:00:00Z',
    embedding: [0.38, 0.71, 0.45, 0.68, 0.54, 0.51, 0.81, 0.68, 0.42, 0.65, 0.81, 0.58, 0.70, 0.88, 0.50, 0.64],
  },
  {
    id: 'kb-12',
    title: 'Cosine Similarity Skill Matching Algorithm Mechanics',
    category: 'Industry Benchmark',
    sourceType: 'skill',
    content: 'SkillBridge uses an N-dimensional cosine similarity matching algorithm between the student candidate skill proficiency vector and the hiring company required skill matrix. Postings with match scores above 85% appear with high-priority match badges and increased visibility in industry applicant dashboards.',
    tags: ['matching algorithm', 'cosine similarity', 'vector search', 'ranking', 'match score'],
    updatedAt: '2026-03-01T00:00:00Z',
    embedding: [0.70, 0.65, 0.72, 0.61, 0.78, 0.74, 0.53, 0.62, 0.71, 0.50, 0.75, 0.76, 0.58, 0.63, 0.79, 0.55],
  },
];
